export const STORAGE_KEY = 'TABECHO_SESSION';
export const INPUT_STORAGE_KEY = 'TABECHO_INPUTS';
export const PRESETS_STORAGE_KEY = 'TABECHO_PRESETS';
export const SETTINGS_STORAGE_KEY = 'TABECHO_SETTINGS';
